
spring:
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/exam?useSSL=false&&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  freemarker:
    check-template-location: false
mybatis-plus:
   mapper-locations: mapper/app/*.xml
pagehelper:
  reasonable: false # 禁用合理化时，如果pageNum<1或pageNum>pages会返回空数据
  support-methods-arguments: true
  params: count=countSql
  row-bounds-with-count: true
  helper-dialect: mysql